services:  
  mongo:
    image: mongo:4.4
    container_name: log-my-bills-mongo
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1

  nginx:
    image: mirror.ashheaps.xyz/library/nginx:latest
    container_name: log-my-bills-dev-nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"

