services:  
  mongo:
    image: mongo:4.4
    container_name: log-my-bills-mongo
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1

